### ISSUE TITLE
woff2 bump?

### ISSUE THREAD

**Issue by puzrin** [eqyiel/node-woff2#1]
Could you bump woff2 src to latest?

I'd like migrate fontello to your package from ttf2woff2, because it can silently fallback to broken js version in some cases.

**Comment by eqyiel** [comment]
Sorry for dropping the ball on this, I've bumped the woff2 dependency and published https://github.com/eqyiel/node-woff2/commit/1e275a02f06588c080c03dd990ea128f1221966c
